# -*- coding: utf-8 -*-
#
# Copyright (C) 2023 Graz University of Technology.
#
# Invenio-i18n is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

name: i18n:pull translations
on:
  workflow_call:
    secrets:
      TRANSIFEX_TOKEN:
        required: true

jobs:
  i18n-pull:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Pull all available translations from transifex
      - name: Pull translated files using transifex client
        uses: transifex/cli-action@v1
        with:
          token: ${{ secrets.TRANSIFEX_TOKEN }}
          args: pull -a -f

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: i18n:pulled translations
          title: i18n:pulled translations
          body: i18n:pulled translations
          branch: 101-translations-pull # name of branch which PR is created from
          delete-branch: true # delete branch once merged,closed
